### ISSUE TITLE
Creating an organisation or moving to fsprojects

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Fabel#11]
Does the project deserve to have its own organisation (I hope so) or will it attract more contributors if moved to fsprojects? I'd love to hear @dsyme opinion on this (and everybody else, of course).

Only one thing is clear, I don't want to have it in my personal repo for the official release :) This is for the community!

**Comment by Krzysztof-Cieslak** [comment]
I would probably move it to fsprojects, and when it becomes popular and successful then move it to own organization... at least that's the way I've used for Ionide.

**Comment by alfonsogarciacaro** [comment]
That makes lot of sense :+1: Now I'd need some guidance on how to move the repo to fsprojects :)

**Comment by Krzysztof-Cieslak** [comment]
Ping @forki

**Comment by alfonsogarciacaro** [comment]
Moving to fsprojects shortly, thanks!
