### ISSUE TITLE
Complete unit tests

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Fabel#3]
The project should include at least as many tests as FunScript. So far I've been copying and adapting unit tests from FunScript repo, basically my removing the quotation brackets `<@@` and `@@>` and adding an assertion with `Util.equal`.

If someone wants to help with this process, please write which file you want to take care of to make sure we don't step on each other's feet. Maybe @MaxWilson can help here too? Thanks!

**Comment by davidpodhola** [comment]
tests are now run in appveyor see #8

**Comment by alfonsogarciacaro** [comment]
We already have around 500 tests so let's deal with the remaining ones on a case by case basis. Closing the issue.
