### ISSUE TITLE
Improve the typescript parser and add definitions to lib/import

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Fabel#4]
Improve the [typescript parser](https://github.com/alfonsogarciacaro/Fabel/blob/master/tools/typescript2fabel.js) and start importing the most common TypeScript definition files (core library, node, React...) to help with the samples.

**Comment by Krzysztof-Cieslak** [comment]
How are/will be typescript's union types handled?

**Comment by alfonsogarciacaro** [comment]
It's still only half-implemented, but my idea is to allow erased union types. At the moment I'm using [custom union types with `Erase` attribute](https://github.com/alfonsogarciacaro/Fabel/blob/master/src/AST/AST.Common.fs#L4-L6), but maybe it's easier to just use the `Choice` type (though erasing Choice will likely cause problems with `Observable.merge` at least). A similar idea is used to represent Babel types, as you can see [here](https://github.com/alfonsogarciacaro/Fabel/blob/master/src/AST/AST.Babel.fs#L225). There's then a JsonConverter to erase the union wrapper when serialising.

[Here](https://github.com/alfonsogarciacaro/Fabel/blob/master/src/FSharp2Fabel.fs#L209), [here](https://github.com/alfonsogarciacaro/Fabel/blob/master/src/FSharp2Fabel.fs#L261-L265) and [here](https://github.com/alfonsogarciacaro/Fabel/blob/master/src/FSharp2Fabel.fs#L302-L307) you can see how the erased unions are supposed to be dealt with (more or less like options).

Of course, this is not written in stone so suggestions are welcome... as long as they're easy to implement and compatible with the rest of the code ;)

**Comment by alfonsogarciacaro** [comment]
Unspecific, closing.
