### ISSUE TITLE
Maybe call it Fable instead?

### ISSUE THREAD

**Issue by cloudRoutine** [alfonsogarciacaro/Fabel#9]
I get the Babel -> Fabel play on words, but Fable is a cooler name :stuck_out_tongue_winking_eye:

**Comment by alfonsogarciacaro** [comment]
That was actually my first option ;) but at the end I decided to be "imaginative" and just replace the first letter with a F. Anyways, my plan is to open some discussions with the community after announcement, including the name (I got used to it though) and the logo, so we'll have soon a chance to vote :)

**Comment by cloudRoutine** [comment]
Sounds good :smile: 

My hope is more F# projects will have names that stand on their own that aren't bound to a heritage in projects from other languages, like how Fix just changed its name to Forge. I think it gives the impression that they're their own entities, unconstrained by the expectations of copying the decisions and designs of their forebearers and frees them to pursue their own distinct form and destiny.

But that's just my silly philosophy :wink:

**Comment by alfonsogarciacaro** [comment]
That's not silly but it makes a lot of sense. As it seems the project is in the wild now, I opened #10 so the community can vote :)
